name: GitHub Actions Demo

on:
  push:
    branches: [ "main" ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "15 6 * * SUN"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Event
        run: echo "{{ github.event_name }}

      - name: branch name
        run: echo ${{ github.ref }}

      - name: checkout
        uses: actions/checkout@v4
        
      - name: List files in repo        
        run: echo ${{ github.repository }}
        
