name: GitHub Actions Demo

on:
  push:
    branches: [ "main" ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "15 6 * * SUN"
  workflow_dispatch:
    inputs: 
      Environment: 
        description: 'Environment to deploy to'
        required: true
        type: environment
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Event
        run: echo "${{ github.event_name }}"

      - name: branch name
        run: echo "${{ github.ref }}"

      - name: checkout
        uses: actions/checkout@v4
        
      - name: List files in repo
        run: |
          echo "Repo ${{ github.repository }} Files:"
          tree

#Test: runs on ubuntu-latest after Build. 
#Only runs when the workflow was triggered manually. 
#Runs on the environment Test. 
#The job writes Testing... to the workflow log.
  Test: 
    runs-on: ubuntu-latest
    needs: build
    if: github.event == 'workflow_dispatch'
    environment: Test
    steps:
      - name: test
        run: echo "Testing... "

#Load-Test: runs on ubuntu-latest after Build.
#Only runs when the workflow was triggered manually.
#Runs on the environment Load-Test.
#The job writes Testing... to the workflow log and sleeps for 15 seconds.
  Load-Test:
    runs-on: ubuntu-latest
    needs: build
    if: github.event == 'workflow_dispatch'
    environment: Load-Test
    steps:
      - name: load-test
        run: | 
          echo 'Testing...'
          sleep 15

#Production: runs on ubuntu-latest after Test and Load-Test. 
#Deploys to the environment Production onyl if this was selected as the input parameter. 
#The environment has the URL https://writeabout.net. 
#To simulate deployment, the job will execute 5 steps. 
#Each step with writes Step x deploying... to the workflow log and sleeps for 10 seconds.
  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    if: github.event.inputs.environment == 'Production' && github.event == 'workflow_dispatch'
    environment: 
      name: Production
      url: https://writeabout.net
    steps:
      - name: step 1
        run: | 
          echo 'step 1 deploying...' 
          sleep 10
      - name: step 2
        run: | 
          echo 'step 2 deploying...' 
          sleep 10
      - name: step 3
        run: | 
          echo 'step 3 deploying...' 
          sleep 10
      - name: step 4
        run: | 
          echo 'step 4 deploying...' 
          sleep 10
      - name: step 5
        run: | 
          echo 'step 5 deploying...' 
          sleep 10
        
